
package com.embriq.webservice.enricher;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-08-29T15:04:43.744+02:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "Bug", targetNamespace = "http://embriq.no/common/bug")
public class Bug_Exception extends Exception {
    
    private com.embriq.webservice.enricher.Bug bug;

    public Bug_Exception() {
        super();
    }
    
    public Bug_Exception(String message) {
        super(message);
    }
    
    public Bug_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Bug_Exception(String message, com.embriq.webservice.enricher.Bug bug) {
        super(message);
        this.bug = bug;
    }

    public Bug_Exception(String message, com.embriq.webservice.enricher.Bug bug, Throwable cause) {
        super(message, cause);
        this.bug = bug;
    }

    public com.embriq.webservice.enricher.Bug getFaultInfo() {
        return this.bug;
    }
}
