package com.embriq.webservice.posten;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-09-02T21:20:55.314+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "LetterService", 
                  wsdlLocation = "http://ole-pc:8088/mockLetterServiceSoapBinding?WSDL",
                  targetNamespace = "http://posten.no/enterprise/letterservice_v1") 
public class LetterService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://posten.no/enterprise/letterservice_v1", "LetterService");
    public final static QName LetterService = new QName("http://posten.no/enterprise/letterservice_v1", "LetterService");
    static {
        URL url = null;
        try {
            url = new URL("http://ole-pc:8088/mockLetterServiceSoapBinding?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LetterService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ole-pc:8088/mockLetterServiceSoapBinding?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public LetterService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LetterService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LetterService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LetterService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LetterService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LetterService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LetterService
     */
    @WebEndpoint(name = "LetterService")
    public LetterService getLetterService() {
        return super.getPort(LetterService, LetterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LetterService
     */
    @WebEndpoint(name = "LetterService")
    public LetterService getLetterService(WebServiceFeature... features) {
        return super.getPort(LetterService, LetterService.class, features);
    }

}
